Add container image build
* had to remove some optimizations from c2e00db to fix build error:

```
ERROR: unable to select packages:
  so:libc.so.6 (no such package):
    required by: .voctoweb-rundeps-20220306.141920[so:libc.so.6]
  so:libdl.so.2 (no such package):
    required by: .voctoweb-rundeps-20220306.141920[so:libdl.so.2]
  so:libm.so.6 (no such package):
    required by: .voctoweb-rundeps-20220306.141920[so:libm.so.6]
  so:libpthread.so.0 (no such package):
    required by: .voctoweb-rundeps-20220306.141920[so:libpthread.so.0]
```

* bump ruby version